name: Deploy Web Interface Projects

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create site folder
        run: |
          mkdir -p "_site"

      # Unit 1 - Normal HTML projects

      - name: Copy Unit 1 projects
        run: |
          mkdir -p "_site/unit1.project"

          cp "unit1.project/project1.html" \
             "_site/unit1.project/project1.html"

          cp "unit1.project/project2.html" \
             "_site/unit1.project/project2.html"


      # Build Unit 2 - Unit 5 React projects

      - name: Build React projects
        shell: bash
        run: |

          for unit in unit2.project unit3.project unit4.project unit5.project
          do

            echo "=============================="
            echo "Processing $unit"
            echo "=============================="

            for project in "$unit"/*
            do

              if [ -d "$project" ] && [ -f "$project/package.json" ]
              then

                echo "Building: $project"

                cd "$project"

                npm install

                if grep -q '"vite"' package.json
          then
         echo "Vite project detected"
         node node_modules/vite/bin/vite.js build
         else
         echo "Create React App project detected"
         npm run build
         fi

                

                cd - > /dev/null

                target="_site/$project"

                mkdir -p "$target"

                # Vite projects
                if [ -d "$project/dist" ]
                then

                  echo "Vite build detected"

                  cp -r "$project/dist"/. "$target"/

                # Create React App projects
                elif [ -d "$project/build" ]
                then

                  echo "Create React App build detected"

                  cp -r "$project/build"/. "$target"/

                else

                  echo "ERROR: No dist or build folder found"
                  exit 1

                fi

              fi

            done

          done


      # Main homepage

      - name: Copy main index
        run: |
          cp index.html "_site/index.html"


      # GitHub Pages

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "_site"


  deploy:

    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4